module.exports = 
[
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 6,
        "RegionName": "Alta",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 6,
        "RegionName": "Alta",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 6,
        "RegionName": "Alta",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 6,
    "Name": "Alta"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 7,
        "RegionName": "Kåfjord",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 7,
        "RegionName": "Kåfjord",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 7,
        "RegionName": "Kåfjord",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 7,
    "Name": "Kåfjord"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 11,
        "RegionName": "Lyngsalpan",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 11,
        "RegionName": "Lyngsalpan",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 11,
        "RegionName": "Lyngsalpan",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 11,
    "Name": "Lyngsalpan"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 8,
        "RegionName": "Tromsø",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 8,
        "RegionName": "Tromsø",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 8,
        "RegionName": "Tromsø",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 8,
    "Name": "Tromsø"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 9,
        "RegionName": "Balsfjord",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 9,
        "RegionName": "Balsfjord",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 9,
        "RegionName": "Balsfjord",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 9,
    "Name": "Balsfjord"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 10,
        "RegionName": "Senja",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 10,
        "RegionName": "Senja",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 10,
        "RegionName": "Senja",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 10,
    "Name": "Senja"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 29,
        "RegionName": "Tamokdalen",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 29,
        "RegionName": "Tamokdalen",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 29,
        "RegionName": "Tamokdalen",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 29,
    "Name": "Tamokdalen"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 12,
        "RegionName": "Bardu",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 12,
        "RegionName": "Bardu",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 12,
        "RegionName": "Bardu",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 12,
    "Name": "Bardu"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 13,
        "RegionName": "Harstad",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 13,
        "RegionName": "Harstad",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 13,
        "RegionName": "Harstad",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 13,
    "Name": "Harstad"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 14,
        "RegionName": "Narvik",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 14,
        "RegionName": "Narvik",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 14,
        "RegionName": "Narvik",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 14,
    "Name": "Narvik"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 15,
        "RegionName": "Vesterålen",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 15,
        "RegionName": "Vesterålen",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 15,
        "RegionName": "Vesterålen",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 15,
    "Name": "Vesterålen"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 16,
        "RegionName": "Lofoten ",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 16,
        "RegionName": "Lofoten ",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 16,
        "RegionName": "Lofoten ",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 16,
    "Name": "Lofoten "
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 31,
        "RegionName": "Svartisen",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 31,
        "RegionName": "Svartisen",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 31,
        "RegionName": "Svartisen",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 31,
    "Name": "Svartisen"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 17,
        "RegionName": "Trollheimen ",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 17,
        "RegionName": "Trollheimen ",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 17,
        "RegionName": "Trollheimen ",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 17,
    "Name": "Trollheimen "
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 18,
        "RegionName": "Romsdal ",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 18,
        "RegionName": "Romsdal ",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 18,
        "RegionName": "Romsdal ",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 18,
    "Name": "Romsdal "
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 19,
        "RegionName": "Sunnmøre ",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 19,
        "RegionName": "Sunnmøre ",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 19,
        "RegionName": "Sunnmøre ",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 19,
    "Name": "Sunnmøre "
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 20,
        "RegionName": "Nordfjord",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 20,
        "RegionName": "Nordfjord",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 20,
        "RegionName": "Nordfjord",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 20,
    "Name": "Nordfjord"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 21,
        "RegionName": "Fjordane",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 21,
        "RegionName": "Fjordane",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 21,
        "RegionName": "Fjordane",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 21,
    "Name": "Fjordane"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 22,
        "RegionName": "Sogn",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 22,
        "RegionName": "Sogn",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 22,
        "RegionName": "Sogn",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 22,
    "Name": "Sogn"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 23,
        "RegionName": "Jotunheimen",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 23,
        "RegionName": "Jotunheimen",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 23,
        "RegionName": "Jotunheimen",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 23,
    "Name": "Jotunheimen"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 24,
        "RegionName": "Voss",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 24,
        "RegionName": "Voss",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 24,
        "RegionName": "Voss",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 24,
    "Name": "Voss"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 25,
        "RegionName": "Hallingskarvet",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 25,
        "RegionName": "Hallingskarvet",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 25,
        "RegionName": "Hallingskarvet",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 25,
    "Name": "Hallingskarvet"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 26,
        "RegionName": "Hemsedalfjella",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 26,
        "RegionName": "Hemsedalfjella",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 26,
        "RegionName": "Hemsedalfjella",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 26,
    "Name": "Hemsedalfjella"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 27,
        "RegionName": "Røldal",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 27,
        "RegionName": "Røldal",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 27,
        "RegionName": "Røldal",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 27,
    "Name": "Røldal"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 28,
        "RegionName": "Rauland",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 28,
        "RegionName": "Rauland",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 28,
        "RegionName": "Rauland",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 28,
    "Name": "Rauland"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 70,
        "RegionName": "Svalbard",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 70,
        "RegionName": "Svalbard",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 70,
        "RegionName": "Svalbard",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 70,
    "Name": "Svalbard"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 69,
        "RegionName": "Finnmark",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 69,
        "RegionName": "Finnmark",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 69,
        "RegionName": "Finnmark",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 69,
    "Name": "Finnmark"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 68,
        "RegionName": "Troms",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 68,
        "RegionName": "Troms",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 68,
        "RegionName": "Troms",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 68,
    "Name": "Troms"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": "runeengeset",
        "AvalancheDanger": null,
        "AvalancheProblems": [
        ],
        "AvalancheWarning": null,
        "DangerLevel": "4",
        "DangerLevelName": "4 Stor",
        "EmergencyWarning": "Ikke gitt",
        "LangKey": 1,
        "MainText": "Store nysnømengder og kuling fra nordvest gir faregrad 4-stor. Et svakt lag ved bakken nord i fylket fra januar gjør at skred kan bli store.",
        "MunicipalityName": "INGEN KOMMUNE",
        "NextWarningTime": "2014-10-31T16:00:00",
        "PublishTime": "2014-10-30T07:00:00",
        "RegId": 14573,
        "RegionId": 67,
        "RegionName": "Nordland",
        "UtmEast": 499169,
        "UtmNorth": 7441926,
        "UtmZone": 30,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 67,
        "RegionName": "Nordland",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 67,
        "RegionName": "Nordland",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 67,
    "Name": "Nordland"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 66,
        "RegionName": "Nord-Trøndelag",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 66,
        "RegionName": "Nord-Trøndelag",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 66,
        "RegionName": "Nord-Trøndelag",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 66,
    "Name": "Nord-Trøndelag"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 65,
        "RegionName": "Sør-Trøndelag",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 65,
        "RegionName": "Sør-Trøndelag",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 65,
        "RegionName": "Sør-Trøndelag",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 65,
    "Name": "Sør-Trøndelag"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 64,
        "RegionName": "Møre og Romsdal",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 64,
        "RegionName": "Møre og Romsdal",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 64,
        "RegionName": "Møre og Romsdal",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 64,
    "Name": "Møre og Romsdal"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 62,
        "RegionName": "Hordaland",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 62,
        "RegionName": "Hordaland",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 62,
        "RegionName": "Hordaland",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 62,
    "Name": "Hordaland"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 61,
        "RegionName": "Rogaland",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 61,
        "RegionName": "Rogaland",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 61,
        "RegionName": "Rogaland",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 61,
    "Name": "Rogaland"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 60,
        "RegionName": "Vest-Agder",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 60,
        "RegionName": "Vest-Agder",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 60,
        "RegionName": "Vest-Agder",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 60,
    "Name": "Vest-Agder"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 59,
        "RegionName": "Aust-Agder",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 59,
        "RegionName": "Aust-Agder",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 59,
        "RegionName": "Aust-Agder",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 59,
    "Name": "Aust-Agder"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 58,
        "RegionName": "Telemark",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 58,
        "RegionName": "Telemark",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 58,
        "RegionName": "Telemark",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 58,
    "Name": "Telemark"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 57,
        "RegionName": "Vestfold",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 57,
        "RegionName": "Vestfold",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 57,
        "RegionName": "Vestfold",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 57,
    "Name": "Vestfold"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 56,
        "RegionName": "Buskerud",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 56,
        "RegionName": "Buskerud",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 56,
        "RegionName": "Buskerud",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 56,
    "Name": "Buskerud"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 55,
        "RegionName": "Oppland",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 55,
        "RegionName": "Oppland",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 55,
        "RegionName": "Oppland",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 55,
    "Name": "Oppland"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 54,
        "RegionName": "Hedmark",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 54,
        "RegionName": "Hedmark",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 54,
        "RegionName": "Hedmark",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 54,
    "Name": "Hedmark"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 53,
        "RegionName": "Oslo",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 53,
        "RegionName": "Oslo",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 53,
        "RegionName": "Oslo",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 53,
    "Name": "Oslo"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 52,
        "RegionName": "Akershus",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 52,
        "RegionName": "Akershus",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 52,
        "RegionName": "Akershus",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 52,
    "Name": "Akershus"
  },
  {
    "AvalancheWarningList": [
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-10-31T17:00:00",
        "PublishTime": "2014-10-31T00:00:00",
        "RegId": 0,
        "RegionId": 51,
        "RegionName": "Østfold",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-10-31T00:00:00",
        "ValidTo": "2014-10-31T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-01T00:00:00",
        "RegId": 0,
        "RegionId": 51,
        "RegionName": "Østfold",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-01T00:00:00",
        "ValidTo": "2014-11-01T23:59:00"
      },
      {
        "AlpineWeather": null,
        "Author": null,
        "AvalancheDanger": null,
        "AvalancheProblems": null,
        "AvalancheWarning": null,
        "DangerLevel": "0",
        "DangerLevelName": null,
        "EmergencyWarning": null,
        "LangKey": 0,
        "MainText": "Ikke vurdert",
        "MunicipalityName": null,
        "NextWarningTime": "2014-11-01T17:00:00",
        "PublishTime": "2014-11-02T00:00:00",
        "RegId": 0,
        "RegionId": 51,
        "RegionName": "Østfold",
        "UtmEast": 0,
        "UtmNorth": 0,
        "UtmZone": 0,
        "ValidFrom": "2014-11-02T00:00:00",
        "ValidTo": "2014-11-02T23:59:00"
      }
    ],
    "Id": 51,
    "Name": "Østfold"
  }
]